[project]
name = "page-swingly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=3.19.2",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
page-swingly = "page_swingly:main"
page-swingly-publish = "page_swingly.publish:main"
page-swingly-validate = "page_swingly.validate:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
